name: catalyst_app
description: A CAT exam performance tracker.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1
  
  # Data Persistence
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Charting
  fl_chart: ^0.68.0
  
  # Utilities
  intl: ^0.19.0
  google_fonts: ^6.2.1
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation for Hive
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true